name: SQL QA Demo
on: 
  workflow_dispatch:
    inputs:
      question:
        description: '输入要查询的问题'
        required: true
        default: "How many employees are there?"

jobs:
  sql-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: sudo apt-get install -y sqlite3

      - name: Initialize Chinook Database
        run: | 
          curl -s https://raw.githubusercontent.com/lerocha/chinook-database/master/ChinookDatabase/DataSources/Chinook_Sqlite.sql | sqlite3 Chinook.db
          ls -lh Chinook.db

      - name: Install Python dependencies
        run: |
          pip install langchain langchain-community langchain-openai python-dotenv

      - name: Run SQL QA
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python sql_qa_demo.py "${{ github.event.inputs.question }}"
